Update manual deployment with extra info
bitcart/bitcart-docs pull request #8
Opened 2022-08-04 19:28 UTC by surfer190

I just went through the manual deployment steps and would like to add a few things:

* The `libsecp256k1-dev` requirement
* Using a virtual environment
* Info about using a process manager

2022-08-04 19:38 UTC, MrNaif2018 requested changes
Wow, thank you very much for those additions! Small review comments

2022-08-04 19:38 UTC, MrNaif2018 commented on deployment/manual.md
> +    python3.9 -m venv env
```suggestion
    python3 -m venv env
```
More generic version

2022-08-04 19:38 UTC, MrNaif2018 commented on deployment/manual.md
> +* The bitcartCC Admin panel runs on port `3000`
```suggestion
* The BitcartCC Admin panel runs on port `3000`
```

2022-08-04 19:38 UTC, MrNaif2018 commented on deployment/manual.md
> +* THe BitcartCC Store runs on port `4000`.
```suggestion
* The BitcartCC Store runs on port `4000`.
```

2022-08-04 20:44 UTC, surfer190 commented
Will do. There are a few more things I must also add.

2022-08-05 19:47 UTC, MrNaif2018 commented
Oh wow! Incredible additions! By the way, is it really possible to specify env vars you set by separating them with `;` ?

As for firewall setup, yeah. 
Well, doesn't bitcart discover merchants API via the default http://localhost:8000 URL? Or do you mean that it works when in local browser, but if you let's say have a server then it won't be accessible? Hmm, well, I used manual deployment method as something close to development setup but with production builds.

2022-08-05 19:56 UTC, surfer190 commented
> is it really possible to specify env vars you set by separating them with ; ?

No it isn't, they must be seperated by a space. My mistake. I corrected it now.

> Or do you mean that it works when in local browser, but if you let's say have a server then it won't be accessible?

Yes works perfect locally but I am setting it up on a remote VM and accessing it over the internet. Should I make that more clear on the docs?

Next step is setting up a wallet to get a `xpub` - must I do this with [electrum](https://electrum.org/#home)?

2022-08-05 19:59 UTC, MrNaif2018 commented
Well, by the way, why did you pick up manual deployment and not docker one? Personal preferences, or to try how it works?

No, you can get xpub with any wallet you want. It might not be an xpub, depends on what chain do you want to use

And yeah, please make it more clear that it's only when you set it up on a VM, if you set it up locally it will work just fine

2022-08-05 19:59 UTC, MrNaif2018 commented
Because since the last customizations, docker system is so customizable that manual deployment is almost never used

2022-08-07 10:09 UTC, MrNaif2018 approved these changes
Thank you very much! Merging!

2022-08-07 10:09 UTC, merged